language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_install:
  - docker pull localstack/localstack
  - docker run --rm -d -p 4566:4566 localstack/localstack
script:
  - set -e
  - npm run lint
  - npm run test
  # setup links for integration testing
  - npm link
  # kick off integration test
  - sleep 5; SLS_DEBUG=1 npm run test:integration
